# Generated by Django 5.0.4 on 2024-04-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RescueOperations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedetails',
            name='state',
            field=models.CharField(default='your_default_value', max_length=100),
        ),
    ]
