# Generated by Django 5.0.4 on 2024-04-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RescueOperations', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
