# Generated by Django 5.0.4 on 2024-04-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RescueOperations', '0005_element_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='latitude',
            field=models.CharField(default='0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='element',
            name='longitude',
            field=models.CharField(default='0.0', max_length=20),
        ),
    ]
